name: Build-Docker

on:
  push:
    branches:
      - 'main'

jobs:
  dotnet_pack_release_job:
    uses: baoduy/ShareWorkflows/.github/workflows/docker-publish.yaml@main
    with:
      dockerFile: 'pulumi.dockerfile'
      context: '.'
      imageName: 'baoduy2412/dev-environments-pulumi'
      platforms: linux/arm64,linux/amd64
    secrets:
      DOCKER_USERNAME: baoduy2412
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}