name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  version: $(date +%s)
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.9.1
      with:
        platforms: linux/arm64,linux/amd64
        
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: baoduy2412
        password: ${{ secrets.DOCKER_TOKEN }}
        ecr: auto
        logout: true
    
    - name: docker pull cache image
      continue-on-error: true
      run: docker pull baoduy2412/dev-environments-pulumi:latest
      
    - name: Build the Docker image
      run: |
        docker buildx build . --file pulumi.dockerfile \
          --tag baoduy2412/dev-environments-pulumi:${{env.version}} \
          --tag baoduy2412/dev-environments-pulumi:latest \
          --cache-from=baoduy2412/dev-environments-pulumi:latest \
          --push --platform=linux/arm64,linux/amd64
        
        
        
    
