name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: baoduy2412
        password: ${{ secrets.DOCKER_TOKEN }}
        ecr: auto
        logout: true
    
    - name: docker pull cache image
      run: docker pull baoduy2412/dev-environments-pulumi:latest
      
    - name: Build the Docker image
      run: |
        docker buildx build . --file pulumi.dockerfile --tag baoduy2412/dev-environments-pulumi:$(date +%s) --cache-from=${{ env.Image_Name }}:latest
        docker image ls
        
    - name: Push Image to Docker Hub
      run: |
        docker tag baoduy2412/dev-environments-pulumi:$(date +%s) baoduy2412/dev-environments-pulumi:latest
        docker push baoduy2412/dev-environments-pulumi --all-tags
        
        
    
