name: gitea-nodejs-docker-build

on:
  push:
    branches:
    - 'main'
    paths:
    - gitea-dind-nodejs.dockerfile

jobs:
  build_job:
    uses: baoduy/ShareWorkflows/.github/workflows/docker-publish.yaml@main
    with:
      dockerFile: 'gitea-dind-nodejs.dockerfile'
      context: '.'
      imageName: 'baoduy2412/gitea-dind-nodejs'
      platforms: linux/arm64,linux/amd64
    secrets:
      DOCKER_USERNAME: baoduy2412
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
