name: toolbox-docker-build

on:
  push:
    branches:
    - 'main'
    paths:
    - toolbox.dockerfile

jobs:
  build_job:
    uses: baoduy/ShareWorkflows/.github/workflows/docker-publish.yaml@main
    with:
      dockerFile: 'toolbox.dockerfile'
      context: '.'
      imageName: 'baoduy2412/toolbox'
      platforms: linux/arm64
    secrets:
      DOCKER_USERNAME: baoduy2412
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
